---
pipeline:

  maven-test:
    image: maven:3.6-jdk-8-alpine
    commands:
    - mvn install

  faker-test:
    image: node
    commands:
    - npm install
    - npm run faker

  graphviz:
    image: node
    commands:
    - npm install
    - npm run viz
